## NLP has the goal of deriving imformation out of natural language

Another common term for nlp is sequence to sequence problem


In [ ]:
# getting the helper function
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

--2023-10-27 08:59:18--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2023-10-27 08:59:18 (87.6 MB/s) - ‘helper_functions.py’ saved [10246/10246]



In [ ]:
from helper_functions import unzip_data , create_tensorboard_callback , plot_loss_curves , compare_historys

In [ ]:
# Download data (same as from Kaggle)
!wget "https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip"



--2023-10-27 08:59:23--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.31.207, 74.125.128.207, 74.125.143.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.31.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  1.29MB/s    in 0.4s    

2023-10-27 08:59:23 (1.29 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [ ]:
import zipfile

with zipfile.ZipFile("/content/nlp_getting_started.zip" , "r") as f:
  f.extractall("/content")


## Visualise the text data

# New section

In [ ]:
import pandas as pd

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

train_df.head(10)

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   
5   8     NaN      NaN  #RockyFire Update => California Hwy. 20 closed...   
6  10     NaN      NaN  #flood #disaster Heavy rain causes flash flood...   
7  13     NaN      NaN  I'm on top of the hill and I can see a fire in...   
8  14     NaN      NaN  There's an emergency evacuation happening now ...   
9  15     NaN      NaN  I'm afraid that the tornado is coming to our a...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1  
5       1  
6       1  
7       1  
8       1  
9       1

In [ ]:
#Shuffle our training data

train_df_shuffle = train_df.sample(frac= 1 ,random_state = 42)

train_df_shuffle

id       keyword                        location  \
2644   3796   destruction                             NaN   
2227   3185        deluge                             NaN   
5448   7769        police                              UK   
132     191    aftershock                             NaN   
6845   9810        trauma           Montgomery County, MD   
...     ...           ...                             ...   
5226   7470  obliteration                         Merica!   
5390   7691         panic                             NaN   
860    1242         blood                             NaN   
7603  10862           NaN                             NaN   
7270  10409     whirlwind  Stamford & Cork (& Shropshire)   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0  
...                                                 ...     ...  
5226  @Eganator2000 There aren't many Obliteration s...       0  
5390  just had a panic attack bc I don't have enough...       0  
860   Omron HEM-712C Automatic Blood Pressure Monito...       0  
7603  Officials say a quarantine is in place at an A...       1  
7270  I moved to England five years ago today. What ...       1  

[7613 rows x 5 columns]

In [ ]:
## What does train dataframe look like

test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [ ]:
## How many examples of each class

train_df.target.value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [ ]:
# if there are imbalanced dataset then look in tensorflow imabalanced dataset

In [ ]:
#how many total samples

len(train_df) , len(test_df)

(7613, 3263)

In [ ]:
# Lets visualise ome random training samples

import random

random_index = random.randint(0 , len(train_df) -5)
for row in train_df_shuffle[["text" , "target"]][random_index:random_index+5].itertuples():
  _, text , target = row
  print(f"target : {target}" , "real disaster" if target > 0 else "not real disaster")
  print(f"text:\n{text}\n")
  print("---\n")

target : 0 not real disaster
text:
her eyes and words are so icy but she burns like rum on the fire

---

target : 1 real disaster
text:
On #ThisDayInHistory in 1862 Confederate ship blown up by crew. Read More http://t.co/IW7ELSzIfZ via @History

---

target : 0 not real disaster
text:
@montetjwitter11 @nolesfan05 @NutsAndBoltsSP I say concern but not panic. Too many games left. And some games left against each other.

---

target : 1 real disaster
text:
Pakistan says army helicopter has crashed in country's restive northwest killing at least 8 http://t.co/QV1RMZI3J1

---

target : 1 real disaster
text:
Turkish troops killed in Kurdish militant 'suicide attack' http://t.co/7old5MJWph

---



In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
train_sentence , val_sentence , train_labels , val_labels = train_test_split(train_df_shuffle["text"].to_numpy(),
                                                                             train_df_shuffle["target"].to_numpy(),
                                                                             test_size = 0.1,
                                                                             random_state = 42)

In [ ]:
train_labels.shape,train_labels.shape

((6851,), (6851,))

In [ ]:
train_sentence[:1] , train_labels[:1]

(array(['@mogacola @zamtriossu i screamed after hitting tweet'],
       dtype=object),
 array([0]))

## Converting  text into numbers
 Embedding ,  vectorisarion , tokenization

In [ ]:
## Test vectorization (tokenization)
train_sentence[:5]

array(['@mogacola @zamtriossu i screamed after hitting tweet',
       'Imagine getting flattened by Kurt Zouma',
       '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
       "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
       'Somehow find you and I collide http://t.co/Ee8RpOahPk'],
      dtype=object)

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

text_vectorizer = TextVectorization(max_tokens = 10000,# show how many words in the vocabulary none detect automatically
                                    standardize = "lower_and_strip_punctuation",
                                    split = "whitespace",
                                    ngrams = None,# create grp of n words
                                    output_mode = "int",# how to map token to numbers
                                    output_sequence_length = None,# pad all to same length
                                    pad_to_max_tokens = True
                                    )



In [ ]:
train_sentence[0].split()

['@mogacola', '@zamtriossu', 'i', 'screamed', 'after', 'hitting', 'tweet']

In [ ]:
# find the average number of tokns in the training tweets

round(sum([len(i.split()) for i in train_sentence ]) / len(train_sentence))

15

In [ ]:
# setup text vectorization variable

max_vocab_length = 10000 # max number of words in our vocabulary
max_length = 15 # max length our seq will be (how mant words from a tewwr a model see)

text_vectorizer = TextVectorization(max_tokens = max_vocab_length,
                                    output_mode = "int" ,
                                    output_sequence_length = max_length)


In [ ]:
# fit the text vectorizer to train data
text_vectorizer.adapt(train_sentence)


In [ ]:
sample_sentence = "There ss a flood in the city"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[ 74,   1,   3, 232,   4,   2, 182,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [ ]:
#choose random sentense and tokenize it

random_sentence = random.choice(train_sentence)
print(random_sentence)
print("\n")
print(text_vectorizer([random_sentence]))


Fur Leather Coats sprite &amp; weapon of choice was a lifestyle chosen back in '02 http://t.co/N9SNJMEVI6


tf.Tensor(
[[   1  703    1 8186   35  263    6 1881   23    3 5222 4009   88    4
  3224]], shape=(1, 15), dtype=int64)


In [ ]:
# get the unique words in the vocab

words_in_vocab = text_vectorizer.get_vocabulary()## get all th eunique words in the training data
top_5_words= words_in_vocab[:5] # most common
bottom_5_words = words_in_vocab[-5:] # least common
top_5_words , bottom_5_words

(['', '[UNK]', 'the', 'a', 'in'],
 ['pages', 'paeds', 'pads', 'padres', 'paddytomlinson1'])

In [ ]:
#[UNK] - unknown token

## Creating embedding

In [ ]:
# input_dim = the size of our vocab
# output_dim = the size of output embedding vector
# input_length = length of the sequence being passed to embedding layer(no. of words)



In [ ]:
from tensorflow.keras import layers

embedding = layers.Embedding(input_dim = max_vocab_length,
                             output_dim = 128,
                             input_length = max_length,
                             )

embedding

In [ ]:
# get random sentence

random_sentence = random.choice(train_sentence)
print(random_sentence[1:4] , end = "\n")
smaple_embedded = embedding(text_vectorizer([random_sentence[1:4]]))

print(smaple_embedded.shape)
print(smaple_embedded)



Kur
(1, 15, 128)
tf.Tensor(
[[[-0.00751842  0.01704839  0.0089891  ...  0.04523708 -0.01109527
    0.01449338]
  [ 0.0117135   0.03059881  0.03807345 ... -0.04170914 -0.02733715
    0.0434033 ]
  [ 0.0117135   0.03059881  0.03807345 ... -0.04170914 -0.02733715
    0.0434033 ]
  ...
  [ 0.0117135   0.03059881  0.03807345 ... -0.04170914 -0.02733715
    0.0434033 ]
  [ 0.0117135   0.03059881  0.03807345 ... -0.04170914 -0.02733715
    0.0434033 ]
  [ 0.0117135   0.03059881  0.03807345 ... -0.04170914 -0.02733715
    0.0434033 ]]], shape=(1, 15, 128), dtype=float32)


## Models
  * Model 1 - feed forward neteork
  * Model 2 - LSTM model
  * Model 3 - GRU model
  * Model 4 - Bidirectional LSTM
  * Model 5 - CNN
  * Model 6 - Transfer Learning
  * Model 7 - As same as model 6 with 10% of data


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline


# create tokenization and modelling pipeline

model_0 = Pipeline([
    ("tfidf" , TfidfVectorizer()),
    ("clf" , MultinomialNB()) # model the text
])


model_0.fit(train_sentence , train_labels )

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [ ]:
# Evaluate
baseline_score = model_0.score(val_sentence , val_labels)
print(f"Our baseline model achives an accuracy of : {baseline_score*100:.2f}%")

Our baseline model achives an accuracy of : 79.27%


In [ ]:
train_df.target.value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [ ]:
# predict
baseline_preds = model_0.predict(val_sentence)
print(baseline_preds[:20])

print(val_labels[:20])


[1 1 1 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 1]
[0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0]


In [ ]:
## Creatting evaluation fuunction
from sklearn.metrics import accuracy_score  , precision_recall_fscore_support

def calculation_results(y_true , y_pred):

  model_accuracy = accuracy_score(y_true , y_pred) * 100
  model_precision , model_recall ,model_f1 , _ = precision_recall_fscore_support(y_true , y_pred ,average = "weighted" )
  model_result_dic = {"accuracy" : model_accuracy , "precision" :model_precision   ,
                      "recall " :model_recall ,
                      "f1_score" :model_f1 }

  return model_result_dic



In [ ]:
# get base line result

baseline_result = calculation_results(val_labels ,  baseline_preds)
baseline_result

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall ': 0.7926509186351706,
 'f1_score': 0.7862189758049549}

## Model_1


In [ ]:
## create tensorboard call back

from helper_functions import create_tensorboard_callback

save_dir = "model_log"


In [ ]:
from tensorflow.keras import layers

inputs = layers.Input(shape = (1,) , dtype = tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(1 , activation = "sigmoid")(x)
model_1 = tf.keras.Model(inputs ,outputs , name = "model_1_dense")



In [ ]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_average_pooling1d (  (None, 128)               0         
 GlobalAveragePooling1D)                                         
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1280129 (4.88 MB)
Trainable params: 128

In [ ]:
model_1.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics = ["accuracy"])


In [ ]:
model_1_history = model_1.fit(x = train_sentence ,
                              y = train_labels,
                              epochs = 5,
                              validation_data = (val_sentence , val_labels),
                              callbacks = [create_tensorboard_callback(dir_name =save_dir,experiment_name ="model_1_dense" )])


Saving TensorBoard log files to: model_log/model_1_dense/20231027-085934
Epoch 1/5
215/215 [==============================] - 24s 74ms/step - loss: 0.6147 - accuracy: 0.6989 - val_loss: 0.5405 - val_accuracy: 0.7625
Epoch 2/5
215/215 [==============================] - 3s 14ms/step - loss: 0.4446 - accuracy: 0.8165 - val_loss: 0.4718 - val_accuracy: 0.7874
Epoch 3/5
215/215 [==============================] - 2s 11ms/step - loss: 0.3483 - accuracy: 0.8608 - val_loss: 0.4614 - val_accuracy: 0.7861
Epoch 4/5
215/215 [==============================] - 2s 9ms/step - loss: 0.2859 - accuracy: 0.8888 - val_loss: 0.4650 - val_accuracy: 0.7808
Epoch 5/5
215/215 [==============================] - 1s 7ms/step - loss: 0.2390 - accuracy: 0.9115 - val_loss: 0.4827 - val_accuracy: 0.7848


In [ ]:
tf.squeeze(tf.round(model_1.predict(val_sentence)))

24/24 [==============================] - 0s 3ms/step


<tf.Tensor: shape=(762,), dtype=float32, numpy=
array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0

In [ ]:
model_1_result = calculation_results(val_labels ,tf.squeeze(tf.round(model_1.predict(val_sentence))) )

24/24 [==============================] - 0s 4ms/step


In [ ]:
import numpy as np
np.array(list(model_1_result.values())) > np.array(list(baseline_result.values()))

array([False, False, False, False])

## Visualised embedding layer


In [ ]:
# get the vocabulary from the text vectorization layer

words_in_vocab = text_vectorizer.get_vocabulary()
len(words_in_vocab) , words_in_vocab[:10]

(10000, ['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is'])

In [ ]:
# get the weighted matrix of embedding layer
#(these are the numerical representations of each token in our training data , which have been learned for 5 epochs)
embed_weights = model_1.get_layer("embedding").get_weights()[0]
embed_weights.shape ## show equal to output layer

(10000, 128)

In [ ]:
embed_weights


array([[-0.00704879,  0.01574119,  0.02756639, ..., -0.03091857,
        -0.04771856,  0.06368256],
       [-0.01348112,  0.01346498,  0.00949247, ...,  0.04268876,
        -0.01870109,  0.0219004 ],
       [-0.04078743,  0.03063099, -0.03586923, ...,  0.05102753,
         0.01429718, -0.00118464],
       ...,
       [ 0.00679809,  0.02401556,  0.04124535, ..., -0.03548636,
        -0.01512755,  0.01542208],
       [-0.04490222, -0.04407899, -0.08757115, ..., -0.00343771,
        -0.01761557,  0.07717165],
       [-0.09995365, -0.10543655, -0.09953634, ...,  0.02504494,
        -0.0914187 ,  0.10331378]], dtype=float32)

In [ ]:
import io

out_v = io.open("vector.tsv" , "w" , encoding = "utf-8")
out_m = io.open("metadata.tsv" , "w" , encoding = "utf-8")

for index , word in enumerate(words_in_vocab):
  if index == 0:
    continue
  vec = embed_weights[index]
  out_v.write('\t'.join([str(x) for x in vec ]) + "\n")
  out_m.write(word + "\n")
out_v.close()
out_m.close()

In [ ]:
## download file to upload to projector

from google.colab import files

files.download("vector.tsv")
files.download("metadata.tsv")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

## RNN

Used for sequence data


## Model_2 LSTM (long short term memory)

In [ ]:
inputs = layers.Input(shape = (1,) , dtype = tf.string ,name = "input_layer")
x = text_vectorizer(inputs)
x = embedding(x)
# print(x.shape)
x = layers.LSTM(units = 16 , return_sequences = True)(x) # when you are stacking RNN layer together you need to return_sequences = True
# print(x.shape)
x = layers.LSTM(units = 16 ,return_sequences = True )(x)
# print(x.shape)
x = layers.LSTM(units = 32 ,return_sequences = True )(x)
x = layers.LSTM(units = 64 )(x)
outputs = layers.Dense(1 , activation = "sigmoid")(x)
# print(x.shape)
model_2 = tf.keras.Model(inputs , outputs , name = "model_2_lstm")





In [ ]:
model_2.summary()

Model: "model_2_lstm"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_layer (InputLayer)    [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 lstm (LSTM)                 (None, 15, 16)            9280      
                                                                 
 lstm_1 (LSTM)               (None, 15, 16)            2112      
                                                                 
 lstm_2 (LSTM)               (None, 15, 32)            6272      
                                                      

In [ ]:
model_2.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics = ["accuracy"])


In [ ]:
model_2.fit(x = train_sentence,
            y = train_labels,
            epochs = 10,
            validation_data = (val_sentence , val_labels),
            callbacks = [create_tensorboard_callback(save_dir , "model_lstm")])

Saving TensorBoard log files to: model_log/model_lstm/20231027-090024
Epoch 1/10
215/215 [==============================] - 21s 53ms/step - loss: 0.2621 - accuracy: 0.8918 - val_loss: 0.5821 - val_accuracy: 0.7651
Epoch 2/10
215/215 [==============================] - 5s 21ms/step - loss: 0.1725 - accuracy: 0.9342 - val_loss: 0.5615 - val_accuracy: 0.7690
Epoch 3/10
215/215 [==============================] - 4s 17ms/step - loss: 0.1384 - accuracy: 0.9448 - val_loss: 0.7948 - val_accuracy: 0.7756
Epoch 4/10
215/215 [==============================] - 3s 15ms/step - loss: 0.1033 - accuracy: 0.9591 - val_loss: 0.8308 - val_accuracy: 0.7651
Epoch 5/10
215/215 [==============================] - 4s 18ms/step - loss: 0.0815 - accuracy: 0.9650 - val_loss: 0.9855 - val_accuracy: 0.7559
Epoch 6/10
215/215 [==============================] - 3s 15ms/step - loss: 0.0655 - accuracy: 0.9710 - val_loss: 1.2575 - val_accuracy: 0.7664
Epoch 7/10
215/215 [==============================] - 3s 14ms/step - lo

In [ ]:
model_2_pred_probs = model_2.predict(val_sentence)
model_2_pred_probs[:10]

24/24 [==============================] - 1s 5ms/step


array([[2.69195909e-04],
       [6.27495289e-01],
       [9.99977946e-01],
       [1.24238774e-01],
       [6.63896790e-05],
       [9.99901056e-01],
       [9.96112406e-01],
       [9.99980807e-01],
       [9.99971867e-01],
       [1.06714368e-01]], dtype=float32)

In [ ]:
model_2_preds = tf.squeeze(tf.round(model_2_pred_probs))
model_2_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
model_2_results = calculation_results(val_labels , model_2_preds)
model_2_results

{'accuracy': 76.64041994750657,
 'precision': 0.7687205386590334,
 'recall ': 0.7664041994750657,
 'f1_score': 0.7638750072248873}

In [ ]:
baseline_result

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall ': 0.7926509186351706,
 'f1_score': 0.7862189758049549}

## Model_3 GRU


Another popular and effective RNN component is the GRU or gated recurrent unit

The GRU cell has similar features to an LSTM cell but has less parameter

In [ ]:
inputs = layers.Input(shape = (1,) , dtype = tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
# print(x.shape)

x = layers.GRU(64 )(x) # when you are stacking RNN layer together you need to return_sequences = True
# print(x.shape)

# x = layers.LSTM(64  , return_sequences = True)(x)
# # print(x.shape)

# x = layers.GRU(64 )(x)
# # print(x.shape)

# x = layers.Dense(64 , activation=  "relu")(x)
# print(x.shape)

# x = layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(1 , activation = "sigmoid")(x)

model_3 = tf.keras.Model(inputs , outputs)



In [ ]:
model_3.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 gru (GRU)                   (None, 64)                37248     
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1317313 (5.03 MB)
Trainable params: 1317313 (5.03 MB)
Non-trainable params: 0 (0.00 Byte)
_______________________

In [ ]:
model_3.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics = ["accuracy"])

In [ ]:
model_3_history = model_2.fit(x = train_sentence,
            y = train_labels,
            epochs = 5,
            validation_data = (val_sentence , val_labels),
            callbacks = [create_tensorboard_callback(save_dir , "model_gru")])

Saving TensorBoard log files to: model_log/model_gru/20231027-090118
Epoch 1/5
215/215 [==============================] - 4s 16ms/step - loss: 0.0485 - accuracy: 0.9778 - val_loss: 1.6893 - val_accuracy: 0.7651
Epoch 2/5
215/215 [==============================] - 4s 18ms/step - loss: 0.0440 - accuracy: 0.9787 - val_loss: 1.5177 - val_accuracy: 0.7690
Epoch 3/5
215/215 [==============================] - 3s 14ms/step - loss: 0.0452 - accuracy: 0.9784 - val_loss: 1.4205 - val_accuracy: 0.7638
Epoch 4/5
215/215 [==============================] - 3s 14ms/step - loss: 0.0385 - accuracy: 0.9799 - val_loss: 1.6265 - val_accuracy: 0.7625
Epoch 5/5
215/215 [==============================] - 7s 31ms/step - loss: 0.0375 - accuracy: 0.9807 - val_loss: 1.6914 - val_accuracy: 0.7625


In [ ]:
model_3_pred_probs = model_3.predict(val_sentence)
model_3_pred_probs[:10]

24/24 [==============================] - 1s 3ms/step


array([[0.5005619 ],
       [0.49969918],
       [0.50629705],
       [0.5088471 ],
       [0.5035517 ],
       [0.5063331 ],
       [0.49759707],
       [0.50485337],
       [0.50274915],
       [0.5087412 ]], dtype=float32)

In [ ]:
model_3_preds = tf.squeeze(  tf.round(model_3_pred_probs))
model_3_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 0., 1., 1., 1., 1., 0., 1., 1., 1.], dtype=float32)>

In [ ]:
model_3_results = calculation_results(val_labels , model_3_preds)
model_3_results

{'accuracy': 43.43832020997375,
 'precision': 0.44203082233849283,
 'recall ': 0.4343832020997375,
 'f1_score': 0.39542811697984015}

## Model_4 (Bidirectional)

In [ ]:
inputs = layers.Input(shape = (1,) , dtype = tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
#x = layers.Bidirectional( layers.LSTM( 64 , return_sequences = True ) )(x)
x = layers.Bidirectional( layers.LSTM(64) )(x)

outputs = layers.Dense(1 , activation = "sigmoid")(x)

model_4 = tf.keras.Model(inputs , outputs , name=  "model_4_bidirectional")


In [ ]:
model_4.summary()

Model: "model_4_bidirectional"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_9 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 bidirectional_2 (Bidirecti  (None, 128)               98816     
 onal)                                                           
                                                                 
 dense_4 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1378945 (5.26 MB)
Trainable par

In [ ]:
model_4.compile(loss = "binary_crossentropy",
                optimizer = tf.keras.optimizers.Adam(),
                metrics = ["accuracy"])

In [ ]:
model_4_history = model_2.fit(x = train_sentence,
            y = train_labels,
            epochs = 5,
            validation_data = (val_sentence , val_labels),
            callbacks = [create_tensorboard_callback(save_dir , "model_bidirection")])

Saving TensorBoard log files to: model_log/model_bidirection/20231027-090512
Epoch 1/5
215/215 [==============================] - 3s 14ms/step - loss: 0.0331 - accuracy: 0.9818 - val_loss: 1.9065 - val_accuracy: 0.7638
Epoch 2/5
215/215 [==============================] - 3s 14ms/step - loss: 0.0312 - accuracy: 0.9825 - val_loss: 2.0939 - val_accuracy: 0.7664
Epoch 3/5
215/215 [==============================] - 4s 19ms/step - loss: 0.0362 - accuracy: 0.9813 - val_loss: 1.2881 - val_accuracy: 0.7612
Epoch 4/5
215/215 [==============================] - 3s 14ms/step - loss: 0.0379 - accuracy: 0.9812 - val_loss: 1.4492 - val_accuracy: 0.7730
Epoch 5/5
215/215 [==============================] - 4s 17ms/step - loss: 0.0347 - accuracy: 0.9823 - val_loss: 1.6509 - val_accuracy: 0.7572


In [ ]:
model_4_pred_probs = model_4.predict(val_sentence)

24/24 [==============================] - 1s 6ms/step


In [ ]:
model_4_preds = tf.squeeze(  tf.round(model_4_pred_probs))
model_4_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 1., 0., 0., 1., 0., 1., 1., 0.], dtype=float32)>

In [ ]:
model_4_results = calculation_results(val_labels , model_4_preds)
model_4_results

{'accuracy': 67.06036745406824,
 'precision': 0.6853365564189777,
 'recall ': 0.6706036745406824,
 'f1_score': 0.6536213852799763}