<a href="https://colab.research.google.com/github/coader-128/Tensorflow/blob/fundamentals/tensorflow_tut_002fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.12.0


In [ ]:
#creating tensor with tf.constant #specifyong the datatype
scalar = tf.constant(7 , dtype = tf.float64)
scalar

<tf.Tensor: shape=(), dtype=float64, numpy=7.0>

In [ ]:
#cgecking number of dimensoin
scalar.ndim

0

In [ ]:
#creating a avector
vector = tf.constant([10,10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [ ]:
#creating a matrix
matrix = tf.constant([[10,10],
                      [23,45]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10 10]
 [23 45]], shape=(2, 2), dtype=int32)
2


In [ ]:
#creating a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [6,9,0]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [6, 9, 0]]], dtype=int32)>

**now we will use tf.Variable  for making variable**

In [ ]:
changeble_tensor = tf.Variable([10,7])
nchangeble_tensor = tf.constant([10,7])
print(changeble_tensor)
print(nchangeble_tensor)


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [ ]:
#chsnging the elemnets of tensor
#  raise error -- changeble_tensor[0] = 7
changeble_tensor[0].assign(7)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#changing unchanglele tensor
nchangeble_tensor[0].assign(7)

AttributeError: ignored

In [ ]:
#creating the random tensors
random_tensors = tf.random.Generator.from_seed(42)
random_tensors = random_tensors.normal(shape = (3,2))
random_tensors

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_tensor = tf.random.Generator.from_seed(43)
random_tensor = random_tensor.normal(shape = (3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284]], dtype=float32)>

In [ ]:
random_tensors == random_tensor

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [ ]:
random_tensor = tf.random.Generator.from_seed(43)
random_tensor = random_tensor.uniform(shape = (3,2))
print(random_tensor)

tf.Tensor(
[[0.1889317  0.52027524]
 [0.8736881  0.46921718]
 [0.63932586 0.6467117 ]], shape=(3, 2), dtype=float32)


In [ ]:
#shuffling the order of tensor
#needed when to shuffel the data

not_shuffeled = tf.constant([[10,7],
                             [10,6],
                             [45,7]])
not_shuffeled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  6],
       [45,  7]], dtype=int32)>

In [ ]:
#shuffeled
tf.random.set_seed(43)#global seed
tf.random.shuffle(value = not_shuffeled , seed = 43)#operatoinal seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [45,  7],
       [10,  6]], dtype=int32)>

In [ ]:
#shuffle along the 1st axis
tf.random.shuffle(value = not_shuffeled , seed = 49)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  6],
       [45,  7]], dtype=int32)>

**read random seed in tensorflow and make random teasors**


**Operations that rely on a random seed actually derive it from two seeds: the** global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.
To illustrate the user-visible effects, consider these examples:

If neither the global seed nor the operation seed is set, we get different results for every call to the random op and every re-run of the program ** **bold text**

In [ ]:
import numpy as np
ones = np.ones(shape = (2,2))
print(ones)

[[1. 1.]
 [1. 1.]]


In [ ]:
#creating tensor with all ones
z = tf.ones((10,1,1) , dtype = tf.int8)
z

<tf.Tensor: shape=(10, 1, 1), dtype=int8, numpy=
array([[[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[1]]], dtype=int8)>

In [ ]:
#with zeros
zeros = tf.zeros((2,2) , dtype = tf.int32)
zeros

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

**Turn numpy array into tensors**

In [ ]:
numpy_array = np.arange(1,25 , dtype = np.int32)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_array , shape = (2,3,4))
print(A)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


**Get information about the tensor**
  * Shape
  * Rank or dim
  * Axis
  * Size


In [ ]:
A.shape, A.ndim

(TensorShape([2, 3, 4]), 3)

In [ ]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
print("Elements along the 0 axis ", A.shape[0])
print("total elemnts in the tensor ",tf.size(A).numpy())

Elements along the 0 axis  2
total elemnts in the tensor  24


**Indexing and expanding tensors**

In [ ]:
tensor_rank_4 = tf.zeros((2,3,4,5) , dtype = tf.int32)
print(tensor_rank_4)

tf.Tensor(
[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]], shape=(2, 3, 4, 5), dtype=int32)


In [ ]:
tensor_rank_4[ :2 , :2 , :2 ,:2 ]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int32)>

In [ ]:
#get each dimension from each other except for the final one
tensor_rank_4[:1 , :1 , : ,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int32, numpy=
array([[[[0],
         [0],
         [0],
         [0]]]], dtype=int32)>

**RESHAPING THE TENSORS**

In [ ]:
rank_2 = tf.random.Generator.from_seed(42)
rank_2 = rank_2.normal(shape = (2,2))
print(rank_2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]], shape=(2, 2), dtype=float32)


In [ ]:
#last elemtnr of tensor
rank_2[:-1].numpy()

array([[-0.7565803 , -0.06854702]], dtype=float32)

In [ ]:
#adding the extra dimnesion

rank_3 = rank_2[... , tf.newaxis]
#rank_3 = rank_2[:,: , tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]]], dtype=float32)>

In [ ]:
#alternative

rank_3 = tf.expand_dims(rank_2 , axis = -1)
rank_3.shape

TensorShape([2, 2, 1])

In [ ]:
#manipulating tensors basic opeation
import tensorflow as tf

tensor = tf.ones(shape = (2,2),dtype = tf.int32)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [ ]:
tensor + 10 #addition -- each elemnet increased by 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 11],
       [11, 11]], dtype=int32)>

In [ ]:
tensor - 4


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-3, -3],
       [-3, -3]], dtype=int32)>

In [ ]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

In [ ]:
tensor / 3

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.33333333, 0.33333333],
       [0.33333333, 0.33333333]])>

In [ ]:
#tensorflow built in function
tf.multiply(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>

In [ ]:
tf.math.multiply(tensor+3 , tensor+2) #lement by elemenet

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 12],
       [12, 12]], dtype=int32)>

In [ ]:
tf.math.add(tensor , tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

**Matrix multiplcation**
  * Its the most common operation with tensor

In [ ]:
#matrix multiolecation
tensor_1 = tf.constant([[1,2],[3,4]])
tensor_2 = tf.constant([[5,6],[7,8]])

print(tf.linalg.matmul(tensor_1 , tensor_2))
print(tensor_1 * tensor_2)


tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [ ]:
# opreation with operator
tensor_1 @ tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [ ]:
tensor_3_2 = tf.ones(shape = (3,2))
tensor_3_2_ = tf.ones(shape = (3,2))+4
tensor_3_2_ @ tf.transpose(tensor_3_2) #with transpose

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]], dtype=float32)>

In [ ]:
tensor_3_2_ = tf.reshape( tensor_3_2_ , shape = (2,3))#wit reshape
tf.linalg.matmul(tensor_3_2 , tensor_3_2_)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]], dtype=float32)>

In [ ]:
# """Matrix dot product and cross product"""

tensor_1 = tf.random.Generator.from_seed(43) #using it to create reproducable tensor
tensor_1 = tensor_1.uniform( shape = (3,3) ,minval = 4 ,maxval = 8 , dtype = tf.int32)
print(tensor_1.numpy())

[[6 5 7]
 [7 6 7]
 [7 6 4]]


In [ ]:
tensor_2 = tf.random.Generator.from_seed(45) #using it to create reproducable tensor
tensor_2 = tensor_2.uniform( shape = (3,3) ,minval = 4 ,maxval = 8 , dtype = tf.int32)
print(tensor_2.numpy())

[[4 5 7]
 [6 4 5]
 [6 7 7]]


In [ ]:
tf.tensordot(tensor_1 , tensor_2 , axes =1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 96,  99, 116],
       [106, 108, 128],
       [ 88,  87, 107]], dtype=int32)>

In [ ]:
# if there is error in different dim then transpose it not reshape

In [ ]:
import tensorflow as tf
#changing the datatype
B = tf.constant([1.5 , 4.6])
C = tf.constant([3,4])
print(B , C)

tf.Tensor([1.5 4.6], shape=(2,), dtype=float32) tf.Tensor([3 4], shape=(2,), dtype=int32)


In [ ]:
B = tf.cast(B , dtype = tf.float16) # hardware runs faster on 16 bit
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 4.6], dtype=float16)>

In [ ]:
C = tf.cast(C , dtype = tf.float64)
C

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([3., 4.])>

 **Aggregating tensors**

  Condensing them from multiple values down to a smaller amount of values.

    * get min
    * get mx
    * get mean
    * get sum

In [ ]:
D = tf.constant([-7.89 , -10])
print(D)
print(tf.abs(D))

tf.Tensor([ -7.89 -10.  ], shape=(2,), dtype=float32)
tf.Tensor([ 7.89 10.  ], shape=(2,), dtype=float32)


In [ ]:
rand = tf.random.Generator.from_seed(43)
rand = rand.uniform((50,) , minval = 0 , maxval = 100 ,dtype = tf.int32 )


In [ ]:
rand.ndim , tf.size(rand) , rand.shape

(1, <tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]))

In [ ]:
#finding the minimum
tf.reduce_min(rand)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#get the max
print("the min val is " , tf.math.reduce_max(rand).numpy() )
print("the max_value is",tf.reduce_mean(rand).numpy())
print("the sum is " ,tf.reduce_sum(rand).numpy())
print("the variance is ",tf.math.reduce_variance(tf.cast(rand, dtype = tf.float32)).numpy())#input tesor must be a float or complex value
print("the standard deviation is ",tf.math.reduce_std(tf.cast(rand, dtype = tf.float32)).numpy())#input tesor must be a float or complex value



the min val is  92
the max_value is 45
the sum is  2284
the variance is  650.2176
the standard deviation is  25.499365


In [ ]:
import tensorflow_probability as tfp
print(tfp.stats.variance(rand).numpy()) # to get variance of int tensor
print(tfp.stats.stddev(tf.cast(rand , dtype = tf.float32).numpy())) #alternative methods


650
tf.Tensor(25.499365, shape=(), dtype=float32)


### Positional Maximum and minimum

In [ ]:
tf.random.set_seed(43)
F = tf.random.uniform(shape = (50,))
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.2733041 , 0.5020257 , 0.6628481 , 0.6473899 , 0.3857293 ,
       0.36172044, 0.5412978 , 0.48597205, 0.8773687 , 0.19192028,
       0.9264002 , 0.89626896, 0.6672703 , 0.47216296, 0.22052324,
       0.88224113, 0.21332026, 0.3742751 , 0.6198429 , 0.67401516,
       0.33629417, 0.04864144, 0.00223255, 0.9375315 , 0.1595205 ,
       0.76488817, 0.5631764 , 0.48775423, 0.4250028 , 0.29910493,
       0.8409952 , 0.6727512 , 0.00153816, 0.4085456 , 0.9261861 ,
       0.18742752, 0.60272205, 0.99417937, 0.42423892, 0.27978897,
       0.9430332 , 0.80545497, 0.06359637, 0.56783044, 0.26592016,
       0.98973536, 0.5452112 , 0.11514163, 0.53635466, 0.6935723 ],
      dtype=float32)>

In [ ]:
tf.argmax(F)#index of max

<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [ ]:
#value at index of the emax
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.99417937>

In [ ]:
tf.math.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99417937>

In [ ]:
F[tf.argmax(F)] == tf.math.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(F)#index of min

<tf.Tensor: shape=(), dtype=int64, numpy=32>

In [ ]:
F[tf.argmax(F)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.99417937>

### Squeezing a tensor removing all the single dimension

In [ ]:
G  = tf.constant(tf.random.uniform(shape = (50,)) , shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.37664938, 0.7430246 , 0.69035363, 0.97365904, 0.0374527 ,
           0.27133918, 0.19803417, 0.67543113, 0.73922336, 0.02532101,
           0.8291918 , 0.48841584, 0.2185278 , 0.8247535 , 0.88936913,
           0.8036902 , 0.38279164, 0.30433893, 0.29234076, 0.2935145 ,
           0.5639998 , 0.9598874 , 0.74853563, 0.25989103, 0.53625417,
           0.2177527 , 0.9593824 , 0.1559279 , 0.16658998, 0.7309809 ,
           0.74731255, 0.86929107, 0.53941727, 0.53889453, 0.57927895,
           0.33802235, 0.32572114, 0.11746407, 0.43904614, 0.10065258,
           0.04531574, 0.14416969, 0.49766517, 0.26956677, 0.65565145,
           0.17797768, 0.14637959, 0.87881744, 0.4267038 , 0.78181314]]]]],
      dtype=float32)>

In [ ]:
G.ndim , G.shape

(5, TensorShape([1, 1, 1, 1, 50]))

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed , G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.37664938, 0.7430246 , 0.69035363, 0.97365904, 0.0374527 ,
        0.27133918, 0.19803417, 0.67543113, 0.73922336, 0.02532101,
        0.8291918 , 0.48841584, 0.2185278 , 0.8247535 , 0.88936913,
        0.8036902 , 0.38279164, 0.30433893, 0.29234076, 0.2935145 ,
        0.5639998 , 0.9598874 , 0.74853563, 0.25989103, 0.53625417,
        0.2177527 , 0.9593824 , 0.1559279 , 0.16658998, 0.7309809 ,
        0.74731255, 0.86929107, 0.53941727, 0.53889453, 0.57927895,
        0.33802235, 0.32572114, 0.11746407, 0.43904614, 0.10065258,
        0.04531574, 0.14416969, 0.49766517, 0.26956677, 0.65565145,
        0.17797768, 0.14637959, 0.87881744, 0.4267038 , 0.78181314],
       dtype=float32)>,
 TensorShape([50]))

### One hot encoading
  One-hot encoding is a technique used to represent categorical data in a binary format, where each category is represented by a unique binary code. This is commonly used in machine learning when dealing with categorical variables in data preprocessing.

  Here's how one-hot encoding works:

  Suppose you have a categorical variable with three categories: "red", "green", and "blue". With one-hot encoding, each category is transformed into a binary vector where only one element is 1 (hot) and the rest are 0 (cold):

  "red" becomes [1, 0, 0]
  "green" becomes [0, 1, 0]
  "blue" becomes [0, 0, 1]

In [ ]:
#create a list of index
some_list = [0,1,2,3]
depth = 4
tf.one_hot(some_list , depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom value for one hot
tf.one_hot(some_list , depth = 4 , on_value = 'deeplearning',off_value = 'sing')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'deeplearning', b'sing', b'sing', b'sing'],
       [b'sing', b'deeplearning', b'sing', b'sing'],
       [b'sing', b'sing', b'deeplearning', b'sing'],
       [b'sing', b'sing', b'sing', b'deeplearning']], dtype=object)>

# squaring and log

In [ ]:
H = tf.range(1 , 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#find the squreroot

In [ ]:
tf.math.sqrt(tf.cast(H , dtype = tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
tf.math.log(tf.cast(H , dtype = tf.float32)) # int32 ot=r int64 not allowed

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Numpy and tensor flow

In [ ]:
import numpy as np

J =  tf.constant(np.arange(1,10,2))
J

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 3, 5, 7, 9])>

In [ ]:
np.array(J)

array([1, 3, 5, 7, 9])

In [ ]:
#default type are a bot different

numpy_J = tf.constant(np.array([3,5,6,7]))
tensor_J = tf.constant([1,2,3,4])
numpy_J.dtype , tensor_J.dtype

(tf.int64, tf.int32)

# how to run code faster

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [ ]:
!nvidia-smi

Sat Aug  5 05:34:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Exercise

In [ ]:
import tensorflow as tf
import numpy as np

#creating scalar , vector , matrix ,tensor
scalar = tf.constant(4 , dtype = tf.int8)
print(scalar)
vector = tf.constant(np.arange(0,6) , shape = (6,) , dtype = tf.int8)
print(vector.ndim , vector , vector.shape )
matrix = tf.constant(np.arange(0,6) , shape = (2,3), dtype= tf.int32)
print(matrix.ndim , matrix.numpy() , matrix.shape)
tensor=  tf.constant(np.arange(0,6) , shape = (2,3,1), dtype= tf.int32)
print(tensor.ndim , tensor.numpy() , tensor.shape)


tf.Tensor(4, shape=(), dtype=int8)
1 tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int8) (6,)
2 [[0 1 2]
 [3 4 5]] (2, 3)
3 [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)
